version: 2.3.1.{build}
branches:
  # whitelist
  only:
    - master
    - develop
image: Windows Server 2019
build: Script
clone_folder: C:\project\wslu
build_script: 
  - ps: wsl --list
  - ps: wsl --help

