version: 2
jobs:
  installtests:
    docker:
      - image: patrick330602/fake_wsl_env
    steps:
      - checkout
      - run:
          name: Pre-building Setup
          command: |
            apt-get update -qq
            apt-get install -qq apt-utils sudo
            bash -x ./configure.sh
      - run:
          name: Build and Install
          command: |
            make
            sudo make install
  linktests:
    docker:
      - image: patrick330602/fake_wsl_env
    steps:
      - checkout
      - run:
          name: Pre-building Setup
          command: |
            apt-get update -qq
            apt-get install -qq apt-utils sudo
            bash -x ./configure.sh
      - run:
          name: Build and Link
          command: |
            make
            sudo make link
  pkgbuilds:
    machine: true
    steps:
      - checkout
      - run:
          name: Install Pre-requisites
          command: |
            sudo apt-get update -qq
            sudo apt-get install -qq apt-utils build-essential rpm
      - run:
          name: Build Package
          command: |
            make
            cd extras/scripts
            sudo bash -x ./builder-deb.sh
            sudo bash -x ./builder-rpm.sh
            mkdir -p /tmp/pkgs
            sudo mv ../../target/* /tmp/pkgs
      - store_artifacts:
            path: /tmp/pkgs
  deploydeb:
    docker:
      - image: circleci/ruby:2.3-jessie
    steps:
      - attach_workspace:
         at: /tmp/pkgs
      - run:
          name: Install packageloud cli
          command: gem install package_cloud
      - run:
          name: Push deb package
          command: package_cloud push whitewaterfoundry/wlinux-setup/debian/buster /tmp/pkgs/*.deb
workflows:
  version: 2
  tests:
    jobs:
      - installtests
      - linktests
  build:
   jobs:
      - pkgbuilds
      - deploydeb
  nightlybuild:
    triggers:
       - schedule:
           cron: "0 0 * * *"
           filters:
             branches:
               only:
                 - develop
    jobs:
      - pkgbuilds
