version: 2
jobs:
  installtests:
    docker:
      - image: patrick330602/fake_wsl_env
    steps:
      - checkout
      - run:
          name: Pre-building Setup
          command: |
            apt-get update -qq
            apt-get install -qq apt-utils sudo
            bash -x ./configure.sh
      - run:
          name: Build and Install
          command: |
            make
            sudo make install
  linktests:
    docker:
      - image: patrick330602/fake_wsl_env
    steps:
      - checkout
      - run:
          name: Pre-building Setup
          command: |
            apt-get update -qq
            apt-get install -qq apt-utils sudo
            bash -x ./configure.sh
      - run:
          name: Build and Link
          command: |
            make
            sudo make link
  pkgbuilds:
    machine: true
    steps:
      - checkout
      - run:
          name: Install Pre-requisites
          command: |
            sudo apt-get update -qq
            sudo apt-get install -qq apt-utils build-essential rpm
      - run:
          name: Build Package
          command: |
            make
            cd extras/scripts
            sudo bash -x ./builder-deb.sh
            sudo bash -x ./builder-rpm.sh
            mkdir -p /tmp/pkgs
            sudo mv ../../target/* /tmp/pkgs
      - store_artifacts:
            path: /tmp/pkgs
      - persist_to_workspace:
            root: /tmp/pkgs
            paths: .
  deploypkg:
    docker:
      - image: circleci/ruby:2.3-jessie
    steps:
      - attach_workspace:
          at: /tmp/pkgs    
      - run:
          name: Install packageloud cli
          command: gem install package_cloud
      - run:
          name: Push deb package for debian buster
          command: package_cloud push whitewaterfoundry/wslu/debian/buster /tmp/pkgs/*.deb
      - run:
          name: Push deb package for debian stretch
          command: package_cloud push whitewaterfoundry/wslu/debian/stretch /tmp/pkgs/*.deb         
      - run:
          name: Push deb package for ubuntu bionic
          command: package_cloud push whitewaterfoundry/wlsu/ubuntu/bionic /tmp/pkgs/*.deb
      - run:
          name: Push deb package for ubuntu cosmic
          command: package_cloud push whitewaterfoundry/wlsu/ubuntu/cosmic /tmp/pkgs/*.deb
      - run:
          name: Push rpm package for fedora 29
          command: package_cloud push whitewaterfoundry/wlsu/fedora/29 /tmp/pkgs/*.rpm
      - run:
          name: Push rpm package for enterprise linux 7
          command: package_cloud push whitewaterfoundry/wlsu/el/7 /tmp/pkgs/*.rpm
      - run:
          name: Push rpm package for scientific linux 7
          command: package_cloud push whitewaterfoundry/wlsu/scientific/7 /tmp/pkgs/*.rpm           
      - run:
          name: Push rpm package for sles 15
          command: package_cloud push whitewaterfoundry/wlsu/sles/15.0 /tmp/pkgs/*.rpm
      - run:
          name: Push rpm package for opensuse 15
          command: package_cloud push whitewaterfoundry/wslu/opensuse/15.0 /tmp/pkgs/*.rpm         
workflows:
  version: 2
  tests:
    jobs:
      - installtests
      - linktests
  build:
   jobs:
      - pkgbuilds
      - deploypkg:
          requires: 
            - pkgbuilds
  nightlybuild:
    triggers:
       - schedule:
           cron: "0 0 * * *"
           filters:
             branches:
               only:
                 - develop
    jobs:
      - pkgbuilds
