version: 2
jobs:
  buildsource:
    docker:
      - image: patrick330602/fake_wsl_env
    steps:
      - checkout
      - run:
          name: Install Pre-requisites
          command: |
            apt-get update -qq
            apt-get install -qq apt-utils mime-support sudo
      - run:
          name: Install via Source Code
          command: |
            cd extras/scripts/
            bash -x ./install.sh
  genpkg:
    machine: true
    steps:
      - checkout
      - run:
          name: Install Pre-requisites
          command: |
            sudo apt-get update -qq
            sudo apt-get install -qq build-essential rpm sudo
      - run:
          name: Build Package
          command: |
            make
            cd extras/scripts
            sudo bash -x ./builder-deb.sh
            sudo bash -x ./builder-rpm.sh
            mkdir -p /tmp/pkgs
            sudo mv ../../target/* /tmp/pkgs
      - store_artifacts:
            path: /tmp/pkgs
workflows:
  version: 2
  build:
   jobs:
      - buildsource
      - genpkg
  nightlybuild:
    triggers:
       - schedule:
           cron: "0 0 * * *"
           filters:
             branches:
               only:
                 - develop
    jobs:
      - genpkg
