version: 2
jobs:
  buildsource:
    docker:
      - image: patrick330602/fake_wsl_env
    steps:
      - checkout
      - run:
          name: Install Pre-requisites
          command: |
            apt-get update -qq
            apt-get install -qq apt-utils mime-support sudo
      - run:
          name: Install via Source Code
          command: |
            cd scripts/
            bash -x ./install.sh
  buildpkg:
    machine: true
    steps:
      - checkout
      - run:
          name: Install Pre-requisites
          command: |
            apt-get update -qq
            apt-get install -qq build-essential rpm sudo
      - run:
          name: Build
          command: |
            make
            cd scripts/
      - run:
          name: Debian Package
          command: |
            bash -x ./builder-deb.sh
      - run:
          name: RPM Package
          command: |
            bash -x ./builder-rpm.sh
      - run: cd ..
      - store_artifacts:
            path: target/*
