version: 2
jobs:
  installtests:
    docker:
      - image: patrick330602/fake_wsl_env
    steps:
      - checkout
      - run:
          name: Pre-building Setup
          command: |
            apt-get update -qq
            apt-get install -qq apt-utils sudo
            bash -x ./configure.sh -a
      - run:
          name: Build and Install
          command: |
            make
            sudo make install
  linktests:
    docker:
      - image: patrick330602/fake_wsl_env
    steps:
      - checkout
      - run:
          name: Pre-building Setup
          command: |
            apt-get update -qq
            apt-get install -qq apt-utils sudo
            bash -x ./configure.sh -a
      - run:
          name: Build and Link
          command: |
            make
            sudo make link
  debbuilds:
    machine: true
    steps:
      - checkout
      - run:
          name: Install Pre-requisites
          command: |
            sudo apt-get update -qq
            sudo apt-get install -qq apt-utils build-essential rpm sudo
      - run:
          name: Build Package
          command: |
            make
            cd extras/scripts
            sudo bash -x ./builder-deb.sh
            mkdir -p /tmp/pkgs
            sudo mv ../../target/* /tmp/pkgs
      - store_artifacts:
            path: /tmp/pkgs
  rpmbuilds:
    docker:
      - image: opensuse:latest
    steps:
      - checkout
      - run:
          name: Install Pre-requisites
          command: |
            zypper update -n
            zypper -n install make rpm sudo
      - run:
          name: Build Package
          command: |
            make
            cd extras/scripts
            sudo bash -x ./builder-rpm.sh
            mkdir -p /tmp/pkgs
            sudo mv ../../target/* /tmp/pkgs
      - store_artifacts:
            path: /tmp/pkgs
workflows:
  version: 2
  build:
   jobs:
      - build
      - genpkg
  nightlybuild:
    triggers:
       - schedule:
           cron: "0 0 * * *"
           filters:
             branches:
               only:
                 - develop
    jobs:
      - genpkg
