version: 2
jobs:
  test:
    docker:
      - image: patrick330602/fake_wsl_env
    steps:
      - checkout
      - run:
          name: Pre-Testing Setup
          command: |
            apt-get update -qq
            apt-get install -qq apt-utils mime-support sudo
            bash -x ./configure.sh -a
      - run:
          name: Test
          command: |
            git submodule init
            git submodule update
            make
            make test
  build:
    docker:
      - image: patrick330602/fake_wsl_env
    steps:
      - checkout
      - run:
          name: Pre-Testing Setup
          command: |
            apt-get update -qq
            apt-get install -qq apt-utils mime-support sudo
            bash -x ./configure.sh -a
      - run:
          name: Install
          command: |
            make
            sudo make install
  genpkg:
    machine: true
    steps:
      - checkout
      - run:
          name: Install Pre-requisites
          command: |
            sudo apt-get update -qq
            sudo apt-get install -qq build-essential rpm sudo
      - run:
          name: Build Package
          command: |
            make
            cd extras/scripts
            sudo bash -x ./builder-deb.sh
            sudo bash -x ./builder-rpm.sh
            mkdir -p /tmp/pkgs
            sudo mv ../../target/* /tmp/pkgs
      - store_artifacts:
            path: /tmp/pkgs
workflows:
  version: 2
  build:
   jobs:
      - build
      - genpkg
  nightlybuild:
    triggers:
       - schedule:
           cron: "0 0 * * *"
           filters:
             branches:
               only:
                 - develop
    jobs:
      - genpkg
