version: 2
jobs:
  buildsource:
    docker:
      - image: patrick330602/fake_wsl_env
    steps:
      - checkout
      - run:
          name: Install Pre-requisites
          command: |
            apt-get update -qq
            apt-get install -qq apt-utils mime-support sudo
      - run:
          name: Install via Source Code
          command: |
            cd scripts/
            bash -x ./install.sh
  builddeb:
    machine: true
    steps:
      - checkout
      - run:
          name: Install Pre-requisites
          command: |
            sudo apt-get update -qq
            sudo apt-get install -qq build-essential rpm sudo
      - run:
          name: Build Package
          command: |
            make
            cd scripts
            sudo bash -x ./builder-deb.sh
      - store_artifacts:
            path: target/*
  buildrpm:
    machine: true
    steps:
      - checkout
      - run:
          name: Install Pre-requisites
          command: |
            sudo apt-get update -qq
            sudo apt-get install -qq build-essential rpm sudo
      - run:
          name: Build Package
          command: |
            make
            cd scripts
            sudo bash -x ./builder-rpm.sh
      - store_artifacts:
            path: target/*
workflows:
  version: 2
  build_and_generate:
    jobs:
      - buildsource
      - builddeb
			- buildrpm
