name: Pakckaging Builds
on: [push]
jobs:
  debbuild:
    name: Debian Package building
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Install Pre-requisites
        run: |
          sudo apt-get update -qq
          sudo apt-get install -qq apt-utils build-essential gzip devscripts debhelper 
      - name: Build Debian Package
        run: |
          mkdir -p debian
          cp -r extras/build/debian/* debian
          BUILD_VER="$(grep 'version=' src/wslu-header | cut -d'=' -f 2 | xargs)"
          BUILD_EXTRA_VER="1"
          # dch --distribution stable --newversion ${BUILD_VER}-${BUILD_EXTRA_VER}
          DEB_BUILD_OPTIONS=nocheck debuild -i -us -uc -b
          mkdir -p /tmp/pkgs
          sudo mv ../wsl* /tmp/pkgs
          ls /tmp/pkgs
  rpmbuild:
    name: RPM Package building
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Install Pre-requisites
        run: |
          sudo apt-get update -qq
          sudo apt-get install -qq apt-utils build-essential rpm gzip
      - name: Build RPM Package
        run: |
          make
          sudo bash -x ./extras/build/builder-rpm.sh
          mkdir -p /tmp/pkgs
          sudo mv ../../target/* /tmp/pkgs