name: Packaging Builds
on: [push]
jobs:
  debbuild:
    name: Debian Package deploying
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Install Pre-requisites
        run: |
          sudo apt-get update -qq
          sudo apt-get install -qq apt-utils build-essential gzip devscripts debhelper 
      - name: Build Debian Package
        run: |
          mkdir -p debian
          cp -r extras/build/debian/* debian
          chmod +x debian/rules
          BUILD_VER="$(grep 'version=' src/wslu-header | cut -d'=' -f 2 | xargs)"
          BUILD_EXTRA_VER="1"
          # dch --distribution stable --newversion ${BUILD_VER}-${BUILD_EXTRA_VER}
          DEB_BUILD_OPTIONS=nocheck debuild -i -us -uc -b
          mkdir -p ./pkgs
          mv ../wsl*.* ./pkgs
  rpmbuild:
    name: RPM Package deploying
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Install Pre-requisites
        run: |
          sudo apt-get update -qq
          sudo apt-get install -qq build-essential tar
      - name: 
        run: bash ./configure.sh --rpm
      - name: deploy RPM source to rpm-wslu
        env:
          GH_TOKEN: ${{ secrets.GIT_DEPLOY_KEY }}
        run: |
          git config --global user.email "me@patrickwu.space"
          git config --global user.name "Jinming Wu, Patrick"
          git clone --depth 1 https://patrick330602:$GH_TOKEN@github.com/wslutilities/rpm-wslu.git rpm-repo
          mkdir -p rpm-repo/SOURCES
          mkdir -p rpm-repo/SPECS
          cp ../tmp_rpmb_d/wslu-*.tar.gz rpm-repo/SOURCES
          cp extras/build/rpm/wslu.spec rpm-repo/SPECS
          git --git-dir=./rpm-repo/.git --work-tree=./rpm-repo add -A
          git --git-dir=./rpm-repo/.git --work-tree=./rpm-repo commit -m "RPM Packaging file update: $(date)"
          git --git-dir=./rpm-repo/.git --work-tree=./rpm-repo push