name: RPM Pakckaging
on: [push]
jobs:
  build:
    name: RPM Package building
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Install Pre-requisites
        run: |
          sudo apt-get update -qq
          sudo apt-get install -qq apt-utils build-essential rpm gzip
      - name: Build RPM Package
        run: |
          make
          cd ./extras/build; sudo bash -x builder-rpm.sh
          mkdir -p /tmp/pkgs
          sudo mv ../../target/* /tmp/pkgs